import "server-only";
import { db, transaction } from "./db";
import { hashPassword } from "./crypto";
import { newId } from "./ids";
import { COINS } from "@/lib/data/coins";

/**
 * First-run seed.
 *
 * Creates the administrator account, a handful of demo traders with wallets,
 * deposit methods, fund requests (including pending ones with proof-of-payment
 * attachments), ledger entries, activity history, announcements and default
 * platform settings — so the console is meaningful the moment it is opened.
 *
 * Runs only when the `users` table is empty; it never overwrites live data.
 */

export const SEED_CREDENTIALS = {
  admin: { email: "admin@quantix.app", password: "Admin@12345", name: "Amara Okafor" },
  user: { email: "jason@quantix.app", password: "Demo@12345", name: "Jason Moreau" },
};

const AVATAR_HUES = [265, 215, 165, 35, 340, 190, 285, 120];

function rng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

const iso = (msAgo: number) => new Date(Date.now() - msAgo).toISOString();
const HOUR = 3600_000;
const DAY = 24 * HOUR;

/** A synthetic "payment receipt" image used for seeded proof-of-payment files. */
function receiptSvg(opts: {
  method: string;
  amount: string;
  reference: string;
  payer: string;
  date: string;
  bank: string;
}): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="960" viewBox="0 0 720 960">
  <rect width="720" height="960" fill="#0f1420"/>
  <rect x="32" y="32" width="656" height="896" rx="22" fill="#151b2b" stroke="#2b3450"/>
  <text x="64" y="104" fill="#8b93ab" font-family="Helvetica,Arial" font-size="20" letter-spacing="4">TRANSFER RECEIPT</text>
  <text x="64" y="176" fill="#2dd4a7" font-family="Helvetica,Arial" font-size="30" font-weight="bold">Payment successful</text>
  <line x1="64" y1="212" x2="656" y2="212" stroke="#2b3450"/>
  <text x="64" y="268" fill="#8b93ab" font-family="Helvetica,Arial" font-size="19">Amount</text>
  <text x="656" y="268" fill="#f4f6fb" font-family="Helvetica,Arial" font-size="30" font-weight="bold" text-anchor="end">${opts.amount}</text>
  <text x="64" y="340" fill="#8b93ab" font-family="Helvetica,Arial" font-size="19">Method</text>
  <text x="656" y="340" fill="#f4f6fb" font-family="Helvetica,Arial" font-size="22" text-anchor="end">${opts.method}</text>
  <text x="64" y="404" fill="#8b93ab" font-family="Helvetica,Arial" font-size="19">Institution</text>
  <text x="656" y="404" fill="#f4f6fb" font-family="Helvetica,Arial" font-size="22" text-anchor="end">${opts.bank}</text>
  <text x="64" y="468" fill="#8b93ab" font-family="Helvetica,Arial" font-size="19">Sender</text>
  <text x="656" y="468" fill="#f4f6fb" font-family="Helvetica,Arial" font-size="22" text-anchor="end">${opts.payer}</text>
  <text x="64" y="532" fill="#8b93ab" font-family="Helvetica,Arial" font-size="19">Reference</text>
  <text x="656" y="532" fill="#f4f6fb" font-family="Helvetica,Arial" font-size="22" text-anchor="end">${opts.reference}</text>
  <text x="64" y="596" fill="#8b93ab" font-family="Helvetica,Arial" font-size="19">Date</text>
  <text x="656" y="596" fill="#f4f6fb" font-family="Helvetica,Arial" font-size="22" text-anchor="end">${opts.date}</text>
  <line x1="64" y1="640" x2="656" y2="640" stroke="#2b3450"/>
  <rect x="64" y="684" width="592" height="120" rx="14" fill="#101624" stroke="#2b3450"/>
  <text x="88" y="730" fill="#8b93ab" font-family="Helvetica,Arial" font-size="18">Submitted to Quantix for review.</text>
  <text x="88" y="766" fill="#5d667d" font-family="Helvetica,Arial" font-size="16">Demo attachment — generated by the platform seeder.</text>
  <text x="64" y="880" fill="#4b5468" font-family="Helvetica,Arial" font-size="16">quantix.app · support@quantix.app</text>
</svg>`;
}

export function seedIfEmpty(): boolean {
  const existing = db().prepare("SELECT COUNT(*) AS c FROM users").get() as { c: number };
  if (existing.c > 0) return false;

  transaction(() => {
    const rand = rng(20260924);
    const now = new Date().toISOString();
    const insertUser = db().prepare(
      `INSERT INTO users
        (id, email, name, password_hash, role, status, kyc_status, phone, country,
         avatar_hue, two_factor, created_at, updated_at, last_login_at, last_login_ip)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    );
    const insertBalance = db().prepare(
      `INSERT INTO balances (user_id, asset, amount, avg_cost, updated_at) VALUES (?, ?, ?, ?, ?)`
    );
    const insertTx = db().prepare(
      `INSERT INTO transactions (id, user_id, type, asset, amount, price, fee, status, note, ref_id, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    );
    const insertFund = db().prepare(
      `INSERT INTO fund_requests
        (id, user_id, kind, method_id, method_name, asset, amount, fee, credit, status,
         reference, payer_name, destination, note, proof_mime, proof_name, proof_size, proof,
         submitted_at, reviewed_at, reviewed_by, review_note)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    );
    const insertActivity = db().prepare(
      `INSERT INTO activity_logs
        (id, user_id, actor_id, action, category, summary, entity_type, entity_id, meta,
         severity, ip, user_agent, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    );
    const insertNotification = db().prepare(
      `INSERT INTO notifications (id, user_id, title, body, kind, href, read, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
    );

    /* ------------------------------- accounts ---------------------------- */
    const adminId = newId("usr");
    insertUser.run(
      adminId,
      SEED_CREDENTIALS.admin.email,
      SEED_CREDENTIALS.admin.name,
      hashPassword(SEED_CREDENTIALS.admin.password),
      "admin",
      "active",
      "verified",
      "+1 415 555 0132",
      "United States",
      285,
      1,
      iso(120 * DAY),
      now,
      iso(2 * HOUR),
      "203.0.113.9"
    );

    const demoId = newId("usr");
    insertUser.run(
      demoId,
      SEED_CREDENTIALS.user.email,
      SEED_CREDENTIALS.user.name,
      hashPassword(SEED_CREDENTIALS.user.password),
      "user",
      "active",
      "verified",
      "+41 79 555 0117",
      "Switzerland",
      265,
      0,
      iso(96 * DAY),
      now,
      iso(26 * HOUR),
      "198.51.100.24"
    );

    const people = [
      { name: "Priya Raghunathan", email: "priya.r@northbridge.io", country: "Singapore", kyc: "verified", status: "active" },
      { name: "Diego Salazar", email: "diego.salazar@mailbox.co", country: "Mexico", kyc: "pending", status: "active" },
      { name: "Tomas Lindqvist", email: "tomas.l@fjordbank.se", country: "Sweden", kyc: "verified", status: "active" },
      { name: "Chloe Bennett", email: "chloe.bennett@fastmail.com", country: "United Kingdom", kyc: "unverified", status: "suspended" },
      { name: "Kwame Mensah", email: "kwame@accratech.gh", country: "Ghana", kyc: "verified", status: "active" },
      { name: "Sofia Marchetti", email: "sofia.marchetti@posta.it", country: "Italy", kyc: "pending", status: "active" },
      { name: "Lukas Weber", email: "lukas.weber@helvetia.ch", country: "Switzerland", kyc: "verified", status: "active" },
      { name: "Aisha Bello", email: "aisha.bello@lagosone.ng", country: "Nigeria", kyc: "unverified", status: "active" },
    ];

    const userIds: string[] = [demoId];
    people.forEach((p, i) => {
      const id = newId("usr");
      userIds.push(id);
      insertUser.run(
        id,
        p.email,
        p.name,
        hashPassword(`Trader@${1000 + i}`),
        "user",
        p.status,
        p.kyc,
        `+${10 + i} 555 01${10 + i}${i}`,
        p.country,
        AVATAR_HUES[i % AVATAR_HUES.length],
        i % 3 === 0 ? 1 : 0,
        iso((90 - i * 9 - Math.floor(rand() * 4)) * DAY),
        now,
        iso(Math.floor(rand() * 72 + 1) * HOUR),
        `${192 + (i % 4)}.0.2.${10 + i}`
      );
    });

    /* ---------------------------- deposit methods ------------------------ */
    const methods = [
      {
        id: newId("mth"),
        name: "Bank transfer (ACH / SEPA)",
        kind: "bank",
        currency: "USD",
        instructions:
          "Send the exact amount from a bank account in your own name. Include your Quantix reference in the payment description — transfers without it take longer to match.",
        accountName: "Quantix Digital Assets Ltd",
        accountNumber: "8842 1170 9934",
        bankName: "Meridian Trust Bank · SWIFT MDTRUS33",
        referencePrefix: "QX",
        minAmount: 100,
        maxAmount: 50_000,
        feePercent: 0,
        processingTime: "Within 2 hours",
        sortOrder: 1,
      },
      {
        id: newId("mth"),
        name: "USDT (TRC-20)",
        kind: "crypto",
        currency: "USDT",
        instructions:
          "Send USDT on the TRON (TRC-20) network only. Assets sent on other networks cannot be recovered. Upload the transaction hash or a wallet screenshot as proof.",
        accountName: "Quantix custody wallet",
        accountNumber: "TQn9Y2khDD95J42FQtQTdwVVRbF5xKzXyH",
        bankName: "Tron network · 1 confirmation",
        referencePrefix: "TRX",
        minAmount: 20,
        maxAmount: 100_000,
        feePercent: 0,
        processingTime: "After 1 confirmation (~5 min)",
        sortOrder: 2,
      },
      {
        id: newId("mth"),
        name: "Mobile money",
        kind: "mobile",
        currency: "USD",
        instructions:
          "Dial *123# or use your operator app, choose “Pay bill”, enter the paybill number and your Quantix reference as the account number. Screenshot the confirmation SMS.",
        accountName: "Quantix Paybill 402 881",
        accountNumber: "402881",
        bankName: "MTN MoMo · Airtel Money",
        referencePrefix: "MM",
        minAmount: 10,
        maxAmount: 5_000,
        feePercent: 0.5,
        processingTime: "Within 30 minutes",
        sortOrder: 3,
      },
      {
        id: newId("mth"),
        name: "Card payment (manual)",
        kind: "card",
        currency: "USD",
        instructions:
          "Use the secure payment link sent to your email, then attach the card receipt. Cards must be issued in your own name; prepaid and gift cards are not accepted.",
        accountName: "Quantix Payments",
        accountNumber: "pay.quantix.app/d/8KQ2",
        bankName: "Stripe checkout",
        referencePrefix: "CARD",
        minAmount: 25,
        maxAmount: 10_000,
        feePercent: 2.4,
        processingTime: "Within 1 hour",
        sortOrder: 4,
      },
      {
        id: newId("mth"),
        name: "Cash at partner branch",
        kind: "other",
        currency: "USD",
        instructions:
          "Visit any Meridian Trust branch with your Quantix ID, deposit cash over the counter and photograph the stamped teller slip.",
        accountName: "Quantix Digital Assets Ltd",
        accountNumber: "8842 1170 9934",
        bankName: "Meridian Trust Bank branches",
        referencePrefix: "CSH",
        minAmount: 200,
        maxAmount: 25_000,
        feePercent: 1,
        processingTime: "Same business day",
        sortOrder: 5,
        enabled: 0,
      },
    ];

    const insertMethod = db().prepare(
      `INSERT INTO deposit_methods
        (id, name, kind, currency, instructions, account_name, account_number, bank_name,
         reference_prefix, min_amount, max_amount, fee_percent, processing_time, enabled,
         sort_order, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    );
    for (const m of methods) {
      insertMethod.run(
        m.id,
        m.name,
        m.kind,
        m.currency,
        m.instructions,
        m.accountName,
        m.accountNumber,
        m.bankName,
        m.referencePrefix,
        m.minAmount,
        m.maxAmount,
        m.feePercent,
        m.processingTime,
        "enabled" in m && m.enabled === 0 ? 0 : 1,
        m.sortOrder,
        iso(60 * DAY),
        now
      );
    }

    /* ------------------------------- wallets ----------------------------- */
    const priceOf = (symbol: string) => COINS.find((c) => c.symbol === symbol)?.price ?? 1;

    const demoWallet: [string, number, number][] = [
      ["USD", 12_480.5, 1],
      ["USDT", 4_200, 1],
      ["BTC", 0.5234, 71_240],
      ["ETH", 4.8721, 2_218.4],
      ["SOL", 58.21, 121.35],
    ];
    for (const [asset, amount, cost] of demoWallet) {
      insertBalance.run(demoId, asset, amount, cost, now);
    }

    userIds.slice(1).forEach((id, i) => {
      const cash = Math.round((400 + rand() * 18_000) * 100) / 100;
      insertBalance.run(id, "USD", cash, 1, now);
      insertBalance.run(id, "USDT", Math.round(rand() * 3_000 * 100) / 100, 1, now);
      if (i % 2 === 0) {
        insertBalance.run(id, "BTC", Number((rand() * 0.6).toFixed(4)), 68_400 + rand() * 6_000, now);
      }
      if (i % 3 === 0) {
        insertBalance.run(id, "ETH", Number((rand() * 6).toFixed(4)), 2_100 + rand() * 400, now);
      }
      if (i % 4 === 1) {
        insertBalance.run(id, "SOL", Number((rand() * 80).toFixed(2)), 110 + rand() * 40, now);
      }
    });

    /* --------------------------- fund requests --------------------------- */
    let fundSeq = 0;
    const addFund = (opts: {
      userId: string;
      methodIndex: number;
      amount: number;
      status: "pending" | "approved" | "rejected" | "cancelled";
      submittedAgo: number;
      reviewedAgo?: number;
      withProof?: boolean;
      kind?: "deposit" | "withdrawal";
      note?: string;
      reviewNote?: string;
      payerName?: string;
    }) => {
      const m = methods[opts.methodIndex];
      const id = newId(opts.kind === "withdrawal" ? "wdr" : "dep");
      const fee = Math.round(opts.amount * (m.feePercent / 100) * 100) / 100;
      const reference = `${m.referencePrefix}-${String(48_210 + fundSeq * 37).slice(0, 6)}`;
      fundSeq += 1;
      const submitted = iso(opts.submittedAgo);
      const user = db()
        .prepare("SELECT name FROM users WHERE id = ?")
        .get(opts.userId) as { name: string };
      const proof =
        opts.withProof === false
          ? null
          : Buffer.from(
              receiptSvg({
                method: m.name,
                amount: `$${opts.amount.toLocaleString("en-US", { minimumFractionDigits: 2 })}`,
                reference,
                payer: opts.payerName ?? user.name,
                date: new Date(Date.now() - opts.submittedAgo).toUTCString().slice(0, 22),
                bank: m.bankName,
              }),
              "utf8"
            );
      insertFund.run(
        id,
        opts.userId,
        opts.kind ?? "deposit",
        m.id,
        m.name,
        m.currency === "USDT" ? "USD" : "USD",
        opts.amount,
        fee,
        Math.round((opts.amount - fee) * 100) / 100,
        opts.status,
        reference,
        opts.payerName ?? user.name,
        opts.kind === "withdrawal" ? "Meridian Trust · 8842 1170 9934" : "",
        opts.note ?? "",
        proof ? "image/svg+xml" : null,
        proof ? `${reference}-receipt.svg` : null,
        proof ? proof.byteLength : null,
        proof,
        submitted,
        opts.reviewedAgo !== undefined ? iso(opts.reviewedAgo) : null,
        opts.status === "approved" || opts.status === "rejected" ? adminId : null,
        opts.reviewNote ?? ""
      );
      return id;
    };

    // Approved history (already reflected in seeded balances)
    addFund({ userId: demoId, methodIndex: 0, amount: 15_000, status: "approved", submittedAgo: 62 * DAY, reviewedAgo: 62 * DAY - 2 * HOUR, withProof: true, reviewNote: "Matched bank statement MD-88213." });
    addFund({ userId: demoId, methodIndex: 1, amount: 4_200, status: "approved", submittedAgo: 21 * DAY, reviewedAgo: 21 * DAY - HOUR, withProof: true, reviewNote: "TRC-20 hash verified on-chain." });
    addFund({ userId: demoId, methodIndex: 2, amount: 750, status: "rejected", submittedAgo: 9 * DAY, reviewedAgo: 9 * DAY - 3 * HOUR, withProof: true, reviewNote: "Sender name does not match the account holder. Refunded to the mobile wallet." });

    // Pending queue for the admin to work through
    const pending = [
      { userId: userIds[1], methodIndex: 0, amount: 8_400, submittedAgo: 40 * 60_000 },
      { userId: userIds[2], methodIndex: 1, amount: 1_250, submittedAgo: 3.2 * HOUR },
      { userId: userIds[4], methodIndex: 2, amount: 320, submittedAgo: 6.5 * HOUR },
      { userId: userIds[6], methodIndex: 3, amount: 2_000, submittedAgo: 22 * HOUR },
      { userId: demoId, methodIndex: 0, amount: 5_000, submittedAgo: 1.4 * HOUR, note: "Same-day wire from my business account." },
      { userId: userIds[8], methodIndex: 1, amount: 980, submittedAgo: 26 * HOUR },
    ];
    const pendingIds = pending.map((p) =>
      addFund({ ...p, status: "pending", withProof: true })
    );

    // One pending request with a missing attachment — exercises the review UI
    addFund({ userId: userIds[3], methodIndex: 0, amount: 4_750, status: "pending", submittedAgo: 5 * HOUR, withProof: false, note: "Proof upload failed twice, sending by email." });

    // Approved deposits for the other demo accounts
    userIds.slice(1, 6).forEach((id, i) => {
      addFund({
        userId: id,
        methodIndex: i % methods.length,
        amount: Math.round((1_500 + rand() * 22_000) / 10) * 10,
        status: "approved",
        submittedAgo: (30 - i * 4) * DAY,
        reviewedAgo: (30 - i * 4) * DAY - 2 * HOUR,
        withProof: true,
        reviewNote: "Verified against bank statement.",
      });
    });

    // Withdrawal requests (pending + settled)
    addFund({ userId: userIds[2], methodIndex: 0, amount: 3_200, status: "pending", submittedAgo: 9 * HOUR, withProof: false, kind: "withdrawal", note: "Paying out to my registered bank account." });
    addFund({ userId: demoId, methodIndex: 0, amount: 1_500, status: "approved", submittedAgo: 14 * DAY, reviewedAgo: 14 * DAY - 5 * HOUR, withProof: false, kind: "withdrawal", reviewNote: "Wire sent, MT103 available on request." });

    /* -------------------------------- ledger ----------------------------- */
    const tradeAssets = ["BTC", "ETH", "SOL"];
    for (const userId of userIds) {
      const trades = 6 + Math.floor(rand() * 10);
      for (let i = 0; i < trades; i++) {
        const asset = tradeAssets[Math.floor(rand() * tradeAssets.length)];
        const buy = rand() > 0.42;
        const amount = Number((rand() * (asset === "BTC" ? 0.25 : asset === "ETH" ? 3 : 40) + 0.001).toFixed(4));
        const price = priceOf(asset) * (0.86 + rand() * 0.24);
        insertTx.run(
          newId("tx"),
          userId,
          buy ? "buy" : "sell",
          asset,
          amount,
          Math.round(price * 100) / 100,
          Math.round(amount * price * 0.001 * 100) / 100,
          "completed",
          `${buy ? "Bought" : "Sold"} ${amount} ${asset} at market`,
          null,
          iso(Math.floor(rand() * 45) * DAY + Math.floor(rand() * 20) * HOUR)
        );
      }
    }

    // Deposit/withdrawal ledger entries mirroring the approved fund requests
    const approvedFunds = db()
      .prepare(
        `SELECT * FROM fund_requests WHERE status = 'approved' ORDER BY submitted_at ASC`
      )
      .all() as Record<string, unknown>[];
    for (const f of approvedFunds) {
      insertTx.run(
        newId("tx"),
        String(f.user_id),
        String(f.kind) === "deposit" ? "deposit" : "withdrawal",
        "USD",
        Number(f.credit),
        1,
        Number(f.fee),
        "completed",
        `${String(f.kind) === "deposit" ? "Deposit" : "Withdrawal"} via ${f.method_name} · ${f.reference}`,
        String(f.id),
        String(f.reviewed_at ?? f.submitted_at)
      );
    }

    /* --------------------------- activity stream ------------------------- */
    const activity = (opts: {
      userId: string;
      actorId?: string;
      action: string;
      category: string;
      summary: string;
      severity?: string;
      entityType?: string;
      entityId?: string;
      meta?: Record<string, unknown>;
      ago: number;
      ip?: string;
    }) =>
      insertActivity.run(
        newId("act"),
        opts.userId,
        opts.actorId ?? opts.userId,
        opts.action,
        opts.category,
        opts.summary,
        opts.entityType ?? null,
        opts.entityId ?? null,
        JSON.stringify(opts.meta ?? {}),
        opts.severity ?? "info",
        opts.ip ?? "198.51.100.24",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/128 Safari/537.36",
        iso(opts.ago)
      );

    // Sign-ins spread over the last two weeks
    for (const userId of userIds) {
      const logins = 3 + Math.floor(rand() * 8);
      for (let i = 0; i < logins; i++) {
        activity({
          userId,
          action: "auth.login",
          category: "auth",
          summary: "Signed in",
          severity: "info",
          ago: Math.floor(rand() * 13) * DAY + Math.floor(rand() * 20) * HOUR,
        });
      }
    }

    activity({ userId: adminId, action: "auth.signup", category: "auth", summary: "Administrator account provisioned", severity: "success", ago: 120 * DAY });
    activity({ userId: demoId, action: "auth.signup", category: "auth", summary: "Account created", severity: "success", ago: 96 * DAY });

    // Fund request lifecycle events
    approvedFunds.forEach((f, i) => {
      activity({
        userId: String(f.user_id),
        action: "deposit.submitted",
        category: "deposit",
        summary: `Submitted a $${Number(f.amount).toLocaleString("en-US")} deposit via ${f.method_name}`,
        severity: "info",
        entityType: "deposit",
        entityId: String(f.id),
        meta: { amount: Number(f.amount), method: f.method_name, reference: f.reference },
        ago: Math.floor((Date.now() - new Date(String(f.submitted_at)).getTime()) / 1000) * 1000,
      });
      activity({
        userId: String(f.user_id),
        actorId: adminId,
        action: "deposit.approved",
        category: "deposit",
        summary: `Deposit of $${Number(f.credit).toLocaleString("en-US")} approved and credited`,
        severity: "success",
        entityType: "deposit",
        entityId: String(f.id),
        meta: { amount: Number(f.credit), reference: f.reference, reviewer: SEED_CREDENTIALS.admin.name },
        ago: Math.max(1000, Math.floor((Date.now() - new Date(String(f.reviewed_at ?? f.submitted_at)).getTime()) / 1000) * 1000),
      });
      if (i === 0) return;
    });

    pendingIds.forEach((id) => {
      const f = db().prepare("SELECT * FROM fund_requests WHERE id = ?").get(id) as Record<string, unknown>;
      activity({
        userId: String(f.user_id),
        action: "deposit.submitted",
        category: "deposit",
        summary: `Submitted a $${Number(f.amount).toLocaleString("en-US")} deposit via ${f.method_name}`,
        severity: "warning",
        entityType: "deposit",
        entityId: id,
        meta: { amount: Number(f.amount), method: f.method_name, reference: f.reference, status: "pending" },
        ago: Math.floor((Date.now() - new Date(String(f.submitted_at)).getTime()) / 1000) * 1000,
      });
    });

    activity({ userId: userIds[3], actorId: adminId, action: "admin.user_status", category: "admin", summary: "Account suspended — chargeback risk flagged by payments team", severity: "warning", entityType: "user", entityId: userIds[3], ago: 2 * DAY, ip: "203.0.113.9" });
    activity({ userId: demoId, action: "trade.executed", category: "trade", summary: "Bought 0.042 BTC at market", severity: "success", entityType: "order", ago: 5 * HOUR });
    activity({ userId: demoId, action: "account.password_changed", category: "security", summary: "Password changed", severity: "critical", ago: 12 * DAY });
    activity({ userId: userIds[7], action: "auth.login_failed", category: "security", summary: "Failed sign-in — incorrect password (3 attempts)", severity: "warning", ago: 30 * 60_000 });
    activity({ userId: userIds[1], action: "account.profile_updated", category: "account", summary: "Updated phone number", severity: "info", ago: 3 * DAY });
    activity({ userId: adminId, actorId: adminId, action: "admin.method_created", category: "admin", summary: "Created deposit method “Mobile money”", severity: "info", entityType: "method", ago: 44 * DAY, ip: "203.0.113.9" });
    activity({ userId: adminId, actorId: adminId, action: "admin.settings_updated", category: "admin", summary: "Raised maximum deposit to $50,000", severity: "info", ago: 9 * DAY, ip: "203.0.113.9" });

    /* ---------------------------- notifications -------------------------- */
    insertNotification.run(newId("ntf"), demoId, "Deposit approved", "Your $4,200.00 USDT deposit has been credited to your USD account.", "success", "/wallet", 0, iso(21 * DAY));
    insertNotification.run(newId("ntf"), demoId, "Deposit rejected", "We could not match your $750.00 mobile money payment. The funds were returned to your wallet.", "error", "/deposits", 0, iso(9 * DAY));
    insertNotification.run(newId("ntf"), demoId, "Deposit under review", "Your $5,000.00 bank transfer is queued for verification.", "warning", "/deposits", 0, iso(1.4 * HOUR));
    insertNotification.run(newId("ntf"), demoId, "Maintenance window on Sunday", "Analytics engine upgrade, 02:00–03:00 UTC. Trading stays online.", "info", "/support", 1, iso(2 * DAY));
    insertNotification.run(newId("ntf"), demoId, "New beta: correlation matrix", "Available now in Analytics.", "info", "/support", 1, iso(4 * DAY));
    for (const id of userIds.slice(1)) {
      insertNotification.run(newId("ntf"), id, "Welcome to Quantix", "Complete your first deposit to start trading.", "info", "/deposits", 0, iso(2 * DAY));
    }

    /* ---------------------------- announcements -------------------------- */
    const insertAnnouncement = db().prepare(
      `INSERT INTO announcements (id, title, body, tag, pinned, published, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`
    );
    insertAnnouncement.run(newId("ann"), "Maintenance window on Sunday", "We are upgrading the analytics engine between 02:00 and 03:00 UTC on Sunday. Trading, deposits and withdrawals stay online; historical charts may be briefly unavailable.", "maintenance", 1, 1, iso(2 * DAY));
    insertAnnouncement.run(newId("ann"), "Manual deposits now support mobile money", "Mobile money payouts are matched within 30 minutes during business hours. Always attach your confirmation screenshot so we can credit you faster.", "feature", 0, 1, iso(6 * DAY));
    insertAnnouncement.run(newId("ann"), "New beta: correlation matrix", "Analytics now ships a 30-day correlation matrix across your holdings. Enable it from Analytics → Beta features.", "beta", 0, 1, iso(4 * DAY));
    insertAnnouncement.run(newId("ann"), "Enhanced account security", "Two-factor authentication and session history are live for every account. We recommend enabling 2FA before your next deposit.", "security", 0, 1, iso(11 * DAY));

    /* -------------------------- platform settings ------------------------ */
    const insertSetting = db().prepare(
      `INSERT INTO app_settings (key, value, updated_at) VALUES (?, ?, ?)
       ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at`
    );
    const settings: [string, string][] = [
      ["platform_name", "Quantix"],
      ["support_email", "support@quantix.app"],
      ["registrations_open", "1"],
      ["min_deposit", "20"],
      ["max_deposit", "50000"],
      ["withdrawal_enabled", "1"],
      ["auto_approve_below", "0"],
      ["maintenance_mode", "0"],
      ["maintenance_message", "We are upgrading our matching engine. Deposits are paused briefly."],
    ];
    for (const [key, value] of settings) insertSetting.run(key, value, now);
  });

  return true;
}
